create table if not exists tblUsers(
   userId integer primary key auto_increment,
   username varchar(100) unique,
   password varchar(100),
   firstname varchar(100),
   lastname varchar(100),
   role varchar(100),
   organisation varchar(100),
   address1 varchar(100),
   address2 varchar(100),
   town varchar(100),
   county varchar(100),
   phone varchar(100),
   mobile varchar(100),
   email varchar(100),
   monday boolean,
   tuesday boolean,
   wednesday boolean,
   thursday boolean,
   friday boolean,
   saturday boolean,
   access_level varchar(100),
   access_cases boolean,
   access_c_log boolean,
   access_cwa_log boolean,
   access_outreach_log boolean,
   access_satisfaction boolean,
   access_user_maintenance boolean,
   access_partners boolean,
   access_reports boolean,
   current_employee boolean,
   notes text
)engine=innodb;
